### ISSUE TITLE
Rewrite project README

### ISSUE THREAD

**Issue by frenchja** [syberia/examples#12]
# Overview

@robertzk @peterhurford 

We can't guarantee that anyone that stumbles upon syberia/examples will have seen the docs or be following the docs.  I propose adding a `Get Started in 2 Minutes` example using Titanic to the documentation.

In addition, should we edit the [Prereqs](https://github.com/syberia/examples#prerequisites) to include less detail about Syberia's components and instead focus on a quick explanation of [lockbox](https://github.com/robertzk/lockbox) and installation?

Last, adding links to concrete file examples to the [Structure](https://github.com/syberia/examples#structure) may help enhance the clarity of that section and highlight the expected difference between an initializer and an application configuration.

# Tasks

- [ ] Relink Syberia to main page instead of Github code in https://github.com/syberia/examples#about-syberia
- [ ] Add file links to https://github.com/syberia/examples#structure
- [ ] Rewrite prerequisites to focus on quick installation for new users
- [ ] Add `Get Started in 2 Minutes` section to main README

**Comment by kirillseva** [comment]
maybe a screencast that demonstrates how to train your first model in 5 minutes? or an asciinema

**Comment by robertzk** [comment]
I agree on all points. Let's get to this next hackathon.
